# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20160305_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=400, verbose_name='\u6807\u9898'),
        ),
    ]
