# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_attachment_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('teacher', '\u6307\u5bfc\u6559\u5e08'), ('bachelor', '\u5728\u8bfb\u672c\u79d1\u751f'), ('master', '\u5728\u8bfb\u7855\u58eb'), ('doctor', '\u5728\u8bfb\u535a\u58eb')], default='master', max_length=50, verbose_name='\u7c7b\u522b'),
        ),
    ]
