# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20160313_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='start_data',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 3, 13, 5, 25, 58, 727435, tzinfo=utc), verbose_name='\u5165\u5b66\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='\u53d1\u5e03\u65e5\u671f'),
        ),
    ]
