# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20160313_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
