# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20160313_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(verbose_name='\u5165\u5b66\u65f6\u95f4'),
        ),
    ]
