# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_auto_20160313_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '\u9879\u76ee\u6216\u7814\u7a76\u65b9\u5411', 'verbose_name_plural': '\u9879\u76ee\u6216\u7814\u7a76\u65b9\u5411'},
        ),
        migrations.AddField(
            model_name='project',
            name='achievement',
            field=models.TextField(blank=True, null=True, verbose_name='\u6210\u679c'),
        ),
        migrations.AddField(
            model_name='project',
            name='ongoing',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u6b63\u5728\u8fdb\u884c'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('project', '\u79d1\u7814\u9879\u76ee'), ('research', '\u5b66\u672f\u7814\u7a76')], default='project', max_length=50, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='cms.Membership', to='cms.Member', verbose_name='\u6210\u5458'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u540d\u79f0'),
        ),
    ]
