# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 05:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20160320_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 20, 5, 42, 13, 690570, tzinfo=utc), verbose_name='\u5f00\u59cb\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
