# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_project_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': '\u6210\u5458\u5173\u7cfb', 'verbose_name_plural': '\u6210\u5458\u5173\u7cfb'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 20, 5, 55, 7, 882574, tzinfo=utc), verbose_name='\u53d1\u5e03\u65e5\u671f'),
            preserve_default=False,
        ),
    ]
