# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20160320_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
    ]
