# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160320_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='/report/', max_length=50, verbose_name='\u5206\u7c7b\u94fe\u63a5'),
            preserve_default=False,
        ),
    ]
