# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='\u9605\u8bfb\u91cf'),
        ),
    ]
