# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_article_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, null=True, verbose_name='\u9605\u8bfb\u91cf'),
        ),
    ]
