# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20160322_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(choices=[('data', '\u6570\u636e\u96c6'), ('program', '\u7a0b\u5e8f\u5de5\u5177')], db_index=True, default='data', max_length=50, verbose_name='\u6587\u4ef6\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('teacher', '\u6307\u5bfc\u6559\u5e08'), ('bachelor', '\u5728\u8bfb\u672c\u79d1\u751f'), ('master', '\u5728\u8bfb\u7855\u58eb'), ('doctor', '\u5728\u8bfb\u535a\u58eb')], db_index=True, default='master', max_length=50, verbose_name='\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('project', '\u79d1\u7814\u9879\u76ee'), ('research', '\u5b66\u672f\u7814\u7a76')], db_index=True, default='project', max_length=50, verbose_name='\u7c7b\u578b'),
        ),
    ]
