# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20160322_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ongoing',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
