# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_downloadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='handle',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5904\u7406'),
        ),
    ]
