#!/bin/bash

NEWVERSION=$1
echo ${NEWVERSION}
DEPLOYCOPY=$2
echo ${DEPLOYCOPY}
DEPLOYDEST=$3
echo ${DEPLOYDEST}
DEPLOYPROJECTNAME=$4
echo ${DEPLOYPROJECTNAME}
DEPLOYFILENAME=$5
echo ${DEPLOYFILENAME}

DEPLOYOUTPUTDIR=${DEPLOYPROJECTNAME}_${NEWVERSION}
echo ${DEPLOYOUTPUTDIR}

mkdir -p ${DEPLOYDEST}
cd ${DEPLOYCOPY}
cp -f ${DEPLOYFILENAME} ${DEPLOYDEST}
cd ${DEPLOYDEST}
mkdir -p ${DEPLOYOUTPUTDIR}
tar -zxvf ${DEPLOYFILENAME} -C ${DEPLOYOUTPUTDIR}
ln -sfT ${DEPLOYOUTPUTDIR} current

cd current

make deploy 
echo "deploy ok"

